// vue/src/pages/Login.vue
<template>
  <div class="hx-form-container">
    <div class="hx-login-template-form">
      <a-form
        id="components-form-demo-normal-login"
        :form="form"
        class="login-form"
        @submit="handleSubmit"
      >
        <a-form-item>
          <a-input
            v-decorator="[
          'userName',
          { rules: [{ required: true, message: 'Please input your username!' }] }
        ]"
            placeholder="Username"
          >
            <a-icon slot="prefix" type="user" style="color: rgba(0,0,0,.25)"/>
          </a-input>
        </a-form-item>
        <a-form-item>
          <a-input
            v-decorator="[
          'password',
          { rules: [{ required: true, message: 'Please input your Password!' }] }
        ]"
            type="password"
            placeholder="Password"
          >
            <a-icon slot="prefix" type="lock" style="color: rgba(0,0,0,.25)"/>
          </a-input>
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" class="login-form-button">Log in</a-button>Or
          <a @click="linkToRegisterPage">register now!</a>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script>
import axios from "axios";
export default {
  data() {
    return {
      listParams: {
        phoneNumber: "",
        password: ""
      }
    };
  },
  beforeCreate() {
    this.form = this.$form.createForm(this);
  },
  methods: {
    handleSubmit(e) {
      e.preventDefault();
      this.form.validateFields((err, values) => {
        if (!err) {
          axios({
            method: "POST",
            url: "/api/user/login",
            data: {
              phoneNumber: values.userName,
              password: values.password
            }
          }).then(res => {
            let resData = res.data;
            if (resData.apiStatus === 0 && resData.sysStatus === 0) {
              this.$router.push({
                path: "/"
              });
            } else {
              this.$message.warning(resData.info);
            }
          });
        }
      });
    },
    linkToRegisterPage() {
      this.$router.push({
        name: "register"
      });
    }
  }
};
</script>

<style scoped lang="less">
.hx-login-template-form {
  width: 50%;
  margin: 200px auto;
  border: 1px solid #ebedf0;
  padding: 42px 24px 50px;
  color: rgba(0, 0, 0, 0.65);
}
#components-form-demo-normal-login .login-form {
  max-width: 300px;
}
#components-form-demo-normal-login .login-form-forgot {
  float: right;
}
#components-form-demo-normal-login .login-form-button {
  width: 100%;
}
</style>

// react/src/views/login/login.jsx
import React, { Component } from "react";
import { Form, Input, Button, Checkbox, Icon } from "antd";
import "./login.less";
import { formatRoute } from "react-router-named-routes";

const FormItem = Form.Item;

const formItemLayout = {
  labelCol: {
    xs: { span: 4 },
    sm: { span: 4 }
  },
  wrapperCol: {
    xs: { span: 20 },
    sm: { span: 20 }
  }
};

const tailFormItemLayout = {
  wrapperCol: {
    sm: {
      span: 20,
      offset: 4
    }
  }
};

class LoginForm extends Component {
  constructor() {
    super();
  }

  handleSubmit = e => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        this.props.history.push("/supplySystem");
      } else {
        console.log(err);
      }
    });
  };

  render() {
    const { getFieldDecorator } = this.props.form;
    return (
      <div className="wrap-login-box box-shadow">
        <Form
          onSubmit={this.handleSubmit}
          style={{
            width: "90%",
            margin: "50px auto"
          }}
        >
          <FormItem label="用户名" {...formItemLayout}>
            {getFieldDecorator("username", {
              rules: [{ required: true, message: "请输入用户名" }],
              validateTrigger: "onBlur"
            })(
              <Input
                size="large"
                prefix={
                  <Icon type="user" style={{ color: "rgba(0,0,0,.25)" }} />
                }
                placeholder="请输入用户名"
              />
            )}
          </FormItem>

          <FormItem label="密码" {...formItemLayout}>
            {getFieldDecorator("password", {
              rules: [{ required: true, message: "请输入密码" }],
              validateTrigger: "onBlur"
            })(
              <Input
                size="large"
                type="password"
                prefix={
                  <Icon type="lock" style={{ color: "rgba(0,0,0,.25)" }} />
                }
                placeholder="请输入密码"
              />
            )}
          </FormItem>

          <FormItem {...tailFormItemLayout}>
            <Button
              size="large"
              type="primary"
              htmlType="submit"
              className="w100-percent"
            >
              登 录
            </Button>
          </FormItem>
        </Form>
      </div>
    );
  }
}

const Login = Form.create()(LoginForm);

export default Login;
